"""store trained models in database

Revision ID: 08073d505e10
Revises: 5e3770825325
Create Date: 2026-10-03 20:19:16.270489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '08073d505e10'
down_revision: Union[str, Sequence[str], None] = '5e3770825325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_blob', sa.LargeBinary().with_variant(mysql.LONGBLOB(), 'mysql'), nullable=True))
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('model_blob')

    # ### end Alembic commands ###
